団体に場所の情報の表示を追加
hibiya-itchief/2024-quaint-app pull request #100
Opened 2024-06-15 01:27 UTC by aozoraUS

場所の情報の表示を/groups/[group.id]/indexに追加

2024-06-15 07:54 UTC, hibiyahibiyahibiya requested changes
![Screenshot_20240615-165128](https://github.com/hibiya-itchief/2024-quaint-app/assets/128669695/46a0a65a-d3a8-48e8-8f6e-a565df619571)
流石に階表示が数字だけはまずいｗ一応「階」だけ付け足しといて
もちろんこのデザインが最終決定ではないだろうと思うんだけど

あと調べるのめんどくさいだけなんだけどさ、floor, placeってnullとかundefinedたりえる？

2024-06-15 08:16 UTC, aozoraUS commented
Floorとplaceはnullになり得ます。団体作成時に必須な情報にはしてないです

2024-06-15 09:10 UTC, hibiyahibiyahibiya commented
そしたらnullのときは不明とかなんか書いておく？

2024-06-16 07:35 UTC, aozoraUS commented
情報なしと表示するように変更しました

2024-06-16 08:02 UTC, hibiyahibiyahibiya approved these changes
v-if="group.floor || group.place"
めっちゃ見逃してたわ
けど、今の情報なしの表示の方が親切だし良いんじゃないかな、ありがとう！！

2024-06-16 08:45 UTC, merged