日付、作成者の位置変更
hibiya-itchief/2024-quaint-app pull request #123
Opened 2024-08-02 08:04 UTC by TaichiSakaki

2024-08-02 11:59 UTC, aozoraUS approved these changes

2024-08-02 12:03 UTC, aozoraUS requested changes
<img width="389" alt="スクリーンショット 2024-08-02 21 02 06" src="https://github.com/user-attachments/assets/d2dabf43-b96a-41e9-9b0b-e5150704ba68">
これってどんな感じのデザインにするっていう話だっけ

2024-08-04 10:11 UTC, aozoraUS approved these changes

2024-08-04 10:11 UTC, merged

2024-08-04 11:31 UTC, TaichiSakaki commented
ありがとう！